Repository dlang/dlang.org, pull requests merged in 2018-05, with the labels that each got.

#2356 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/2.080.0.dd
  download.dd
Labels: auto-merge

#2357 Bump archive version to 2.080
  js/listanchors.js
Labels: Trivial, auto-merge

#2360 Error for implicit comparison of different enums
  deprecate.dd
Labels: Trivial

#2359 Error for implicit string concatenation
  deprecate.dd
Labels: Trivial, Waiting for DMD PR, auto-merge

#2362 Fix broken link
  spec/template.dd
Labels: auto-merge

#2364 Remove old & invalid msie < 9 support code
  dlang.org.ddoc
  js/run.js
Labels: Bug Fix, auto-merge

#2370 Remove DConf announcement from the index
  index.dd
Labels: auto-merge

#2351 Fix Issue 16206 - traits getOverloads fails when one of the overload is a templatized function
  spec/traits.dd
Labels: Bug Fix, auto-merge
