Repository dlang/dlang.org, pull requests merged in 2018-03, with the labels that each got.

#2256 State of D: link to the blog article
  index.dd
Labels: Trivial

#2246 Update the Objective-C documentation with support for class methods
  spec/objc_interface.dd
Labels: Spec / content, Waiting for DMD PR, auto-merge

#2204 Improve Compile-time sequences docs
  articles/ctarguments.dd
  articles/index.dd
  dlang.org.ddoc
  tuple.dd
Labels: Spec / content

#2195 Remove PHOBOS macro in favor in REF
  dlang.org.ddoc
  spec/arrays.dd
  spec/cpp_interface.dd
  spec/latex.ddoc
  spec/property.dd
Labels: Trivial, auto-merge

#2270 fix import paths for dmd-${LATEST}
  posix.mak
Labels: Blocking other work, auto-merge

#2269 Add badge to Bugzilla
  README.md
Labels: auto-merge

#2268 Remove ddoc workarounds
  ddoc/source/preprocessor.d
Labels: Trivial, auto-merge

#2276 Bump archives to 2.079
  js/listanchors.js
Labels: Trivial, auto-merge

#2271 fix Issue 18568 - partially overlapping assignments have undefined be…
  spec/expression.dd
Labels: Bug Fix, auto-merge

#2255 Include pending.dd in the changelog footer generation
  ddoc/source/preprocessor.d
Labels: Blocking other work

#2274 Update high-level vision link
  index.dd
Labels: Trivial

#2273 Add OpenCollective backers to foundation/sponsors
  foundation/sponsors.dd
Labels: auto-merge

#2279 Remove volatile keyword from the lexer documentation
  spec/lex.dd
Labels: Trivial, auto-merge

#2285 Fix link in changelog for 2.079.0.
  changelog/2.079.0.dd
Labels: auto-merge

#2275 Fix Issue 18603 - Update minimally required version for macOS
  dcompiler.dd
Labels: Bug Fix, Trivial, auto-merge

#2281 Update struct.dd - postblit documentation
  spec/struct.dd
Labels: Vision

#2286 Remove auto-cloning of Phobos on start
  posix.mak
Labels: auto-merge

#2296 Add $(TAB) macro
  html.ddoc
Labels: auto-merge

#2292 Add snap to the third-party downloads
  download.dd
  images/snapcraft_logo.png
  posix.mak
Labels: auto-merge

#2297 Move $(TAB) to a better position in html.ddoc
  html.ddoc
Labels: Trivial, auto-merge

#2298 Fix quotations in struct.dd
  spec/struct.dd
Labels: auto-merge

#2300 update gpg keys
  d-keyring.gpg
  d-keyring.gpg.sig
  gpg_keys.dd
  posix.mak
Labels: auto-merge

#2305 Fix indendation in the new DBlog.xml tools + move all other build scripts to tools/
  posix.mak
  tools/check_ddoc.d
  tools/chmgen.d
  tools/ddoc_xml_extractor.d
  tools/dspec_tester.d
  tools/modlist.d
  win32.mak
Labels: auto-merge

#2301 [Spec] Clarify `(void*) - (void*)`
  spec/expression.dd
Labels: Spec / content, Trivial

#2302 Fix Issue 18602 - [Better C] docs (duplicate "Dynamic arrays")
  spec/betterc.dd
Labels: Bug Fix, Trivial

#2287 Expose runtime docs on the released docs
  css/style.css
  dlang.org.ddoc
  posix.mak
  tools/modlist.d
Labels: auto-merge

#2291 Add D's docker image to the third-party downloads
  download.dd
  images/docker_logo.png
  posix.mak
Labels: auto-merge

#2309 Remove outdated Chocolatey package
  download.dd
  images/chocolatey_logo.png
Labels: auto-merge

#2304 DConf front page: registration is open
  index.dd
Labels: Trivial, auto-merge

#2318 [trivial] apidocs: fix serve command
  dpl-docs/source/ddox_main.d
Labels: Trivial, auto-merge

#2317 Remove compatibility --html-style=pretty flag
  dpl-docs/source/app.d
Labels: auto-merge
