Repository dlang/dlang.org, pull requests merged in 2018-02, with the labels that each got.

#2176 Fix trailing parenthesis + add test
  articles/cpptod.dd
  check_ddoc.d
  posix.mak
Labels: Blocking other work, auto-merge

#2194 Use LINK2 instead of direct a href for REF macros
  dlang.org.ddoc
Labels: Blocking other work, auto-merge

#2200 [unbreak nightlies] Run the full chmgen script to avoid regressions
  chm-nav.dd
  ddoc_preprocessor.d
  posix.mak
  std.ddoc
Labels: Blocking other work

#2203 [preparation] add an edit button to changelog entries
  changelog/changelog.ddoc
  changelog/pending.ddoc
Labels: Blocking other work, auto-merge

#2197 Provide direct link to Bugzilla on a 404 page
  404.dd
  dlang.org.ddoc
Labels: auto-merge

#2208 Fix broken image src in safe.dd
  articles/safed.dd
Labels: Trivial, auto-merge

#2207 cent and ucent missing in the list BasicTypeX
  spec/declaration.dd
Labels: Spec / content, Trivial, auto-merge

#2138 arrays.dd: better wording
  spec/arrays.dd
Labels: Spec / content

#2171 Move verbose files listing to the middle
  dcompiler.dd
Labels: auto-merge

#2154 Always display the download icon
  download.dd
Labels: auto-merge

#2198 Add DConf to the D Language Foundation menu
  dlang.org.ddoc
  foundation/index.dd
Labels: auto-merge

#2211 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/2.078.2.dd
  changelog/2.078.3.dd
Labels: auto-merge

#2209 Clarify behavior of debug statements
  spec/version.dd
Labels: auto-merge

#2205 Support @nogc in debug{} blocks
  spec/function.dd
Labels: Spec / content, auto-merge

#2202 Add install.sh to the CLI reference menu
  dlang.org.ddoc
  install.dd
Labels: auto-merge

#2214 move Special Keywords to expression.dd
  spec/expression.dd
  spec/lex.dd
  spec/traits.dd
Labels: Trivial, auto-merge

#2215 Remove GSoC 2018 from the Foundation page
  dlang.org.ddoc
  foundation/index.dd
Labels: Trivial, auto-merge

#2213 posix.mak: Add DMan tags to dautotest target
  chmgen.d
  dlang.org.ddoc
  posix.mak
  spec/contracts.dd
  spec/ddoc.dd
  spec/errors.dd
  spec/expression.dd
  spec/iasm.dd
  spec/interfaceToC.dd
  spec/objc_interface.dd
Labels: auto-merge

#2219 Remove --only-tag from d-latest.tag
  posix.mak
Labels: auto-merge

#1941 Fix Issue 9433 - Deprecate delete
  deprecate.dd
  spec/class.dd
  spec/expression.dd
  spec/function.dd
  spec/interface.dd
Labels: @andralex, Bug Fix, Needs Approval

#2220 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/2.079.0_pre.dd
  download.dd
Labels: auto-merge

#2069 Remove the assert->writeln pipeline in favor of the DDoc wrapper
  ddoc/.gitignore
  ddoc/dub.sdl
  ddoc/dub.selections.json
  ddoc/source/assert_writeln_magic.d
  ddoc/source/preprocessor.d
  dpl-docs/dub.json
  dpl-docs/source/app.d
  dpl-docs/source/ddox_main.d
  posix.mak
Labels: Blocking other work, auto-merge

#2225 Update dub.selections.json files
  ddoc/dub.selections.json
  dpl-docs/dub.selections.json
Labels: auto-merge

#2146 Update docs to highlight lambda comparison
  spec/traits.dd
Labels: Spec / content

#2221 Add a release schedule to the changelog pages
  changelog/changelog.ddoc
  changelog/release-schedule.dd
  posix.mak
Labels: auto-merge

#2235 Add big, shiny banner DConf submission banner
  images/banner_dconf_submission.png
  index.dd
  posix.mak
Labels: auto-merge

#2222 embed dlang calendar on dlang.org/calendar
  calendar.dd
  dlang.org.ddoc
  posix.mak
Labels: auto-merge, organizations-page

#2243 Add a html-verbatim target analogous to html
  posix.mak
Labels: auto-merge

#2237 Revert "Update spec for multiple selective imports"
  spec/module.dd
Labels: auto-merge

#2240 Add text: 'Open in IDE' to the Phobos run.dlang.io buttons
  css/style.css
  js/run_examples.js
Labels: auto-merge

#2245 Revert "Update spec for multiple selective imports"
  spec/module.dd
Labels: auto-merge

#2169 spec update following allowing default valued parameters after template variadics
  spec/template.dd
Labels: Spec / content, auto-merge

#2249 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/2.079.0_pre.dd
  download.dd
Labels: auto-merge

#2184 Add contributor hints and explanation of pending.dd
  changelog/pending.ddoc
  posix.mak
Labels: Trivial, UX, auto-merge

#2228 add links for Integer Promotions and Usual Arithmetic Conversions
  spec/expression.dd
Labels: auto-merge

#2247 [trivial] Fix using *sequence* in expression.dd
  spec/expression.dd
Labels: Spec / content, Trivial, auto-merge

#2201 Title font shrinks if too long
  css/html-skeleton.css
  css/style.css
  html.ddoc
  std.ddoc
Labels: auto-merge

#2252 Use correct HTML for BEST_PRACTICE
  dlang.org.ddoc
  ebook.ddoc
  spec/latex.ddoc
  spec/spec.ddoc
Labels: Bug Fix, Ddoc, auto-merge

#2216 add __traits(isReturnOnStack, func)
  spec/traits.dd
Labels: Spec / content, auto-merge

#2253 [trivial] Remove runnable block for the first example in spec/arrays
  spec/arrays.dd
Labels: Trivial, auto-merge

#2254 [Trivial] Remove DConf18 banner
  images/banner_dconf_submission.png
Labels: Trivial, auto-merge
