Repository dlang/dlang.org, pull requests merged in 2018-11, with the labels that each got.

#2501 Fix `do` being optional after a contract statement
  spec/function.dd
Labels: auto-merge

#2487 fix Issue 10692 - Deprecation isn't checked using alias this
  spec/class.dd
Labels: Bug Fix, auto-merge

#2503 Merge remote-tracking branch 'upstream/stable' into merge_stable
  posix.mak
Labels: auto-merge

#2506 update nightlies download url to downloads.dlang.org
  download.dd
Labels: auto-merge

#2508 Remove D_HardDoubleFloat version identifier.
  spec/version.dd
Labels: Trivial, auto-merge

#2465 Undocument Pascal calling convention
  spec/abi.dd
  spec/attribute.dd
  spec/traits.dd
Labels: 72h no objection -> merge

#2510 Fix typo in statement.dd
  spec/statement.dd
Labels: auto-merge

#2325 Spec change for Issue 18474
  spec/struct.dd
Labels: auto-merge

#2507 Add more traits doc examples & make existing examples runnable
  js/run.js
  spec/traits.dd
  tools/dspec_tester.d
Labels: auto-merge

#2511 Don't pluralize with apostrophe s, plus a few other apostrophe fixes
  articles/cpptod.dd
  articles/d-array-article.dd
  articles/d-floating-point.dd
  articles/hijack.dd
  articles/rationale.dd
  articles/regular-expression.dd
  articles/templates-revisited.dd
  articles/variadic-function-templates.dd
  changelog/2.054.dd
  changelog/2.063.dd
  changelog/2.067.0.dd
  changelog/2.068.0.dd
  changelog/2.072.0.dd
  changelog/2.081.0.dd
  dcompiler.dd
  ddoc/source/assert_writeln_magic.d
  foundation/upb-scholarship.dd
  htod.dd
  overview.dd
  spec/abi.dd
  spec/attribute.dd
  spec/const3.dd
  spec/cpp_interface.dd
  spec/ddoc.dd
  spec/garbage.dd
  spec/interfaceToC.dd
  spec/property.dd
  spec/simd.dd
  spec/statement.dd
  spec/traits.dd
Labels: auto-merge

#2478 Fix mistake in C++ code
  articles/cpptod.dd
Labels: auto-merge

#2513 Fix __traits(getFunctionAttributes) example
  spec/traits.dd
Labels: auto-merge

#2514 fix issue 19374 - TypeVector undefined in grammar
  spec/declaration.dd
Labels: Bug Fix, auto-merge

#2515 Fix issue 19321
  spec/struct.dd
Labels: auto-merge
