Repository dlang/dlang.org, pull requests merged in 2018-10, with the labels that each got.

#2479 Add two new sponsors
  foundation/sponsors.dd
Labels: auto-merge

#2482 Update sponsors list
  foundation/sponsors.dd
Labels: auto-merge

#2483 DDox: Fix fall-back JS code for loading jQuery
  dpl-docs/views/layout.dt
Labels: auto-merge

#2473 Additional keys for getTargetInfo
  spec/traits.dd
Labels: auto-merge

#2486 Add guideline for contracts
  dstyle.dd
Labels: Spec / content, auto-merge

#2488 DStyle: Adjust guidance for contracts
  dstyle.dd
Labels: Spec / content

#2490 adjust contracts documentation examples to match dstyle
  spec/contracts.dd
Labels: D Style, Spec / content, auto-merge

#2493 Add changelog clarifications from forum
  changelog/2.083.0_pre.dd
Labels: auto-merge

#2494 Add edit buttons for the changelog entries to the prerelease changelog
  changelog/prerelease.ddoc
Labels: auto-merge

#2495 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/2.083.0_pre.dd
  download.dd
Labels: auto-merge

#2497 Bump the host compiler to 2.082.1
  posix.mak
Labels: auto-merge

#2496 Improve the dlang.org changelog setup
  changelog/prerelease.ddoc
  ddoc/dub.sdl
  ddoc/source/assert_writeln_magic.d
  ddoc/source/preprocessor.d
Labels: Easy Review
