Repository dlang/dlang.org, pull requests merged in 2018-07, with the labels that each got.

#2402 Change deprecated C array syntax to D array syntax in the spec example
  spec/arrays.dd
Labels: Blocking other work, auto-merge

#2290 Modernize dcompiler documentation
  dcompiler.dd
Labels: 72h no objection -> merge, auto-merge

#2404 Fix Issue 17580 - Marking methods as synchronized is allowed despite spec
  spec/class.dd
Labels: auto-merge

#2405 Include interface files in the DDox build
  posix.mak
Labels: Blocking other work, auto-merge

#2406 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/2.081.0_pre.dd
  download.dd
Labels: auto-merge

#2306 Fix Issue 2473, 10941 - Linux system install instructions incorrect
  dcompiler.dd
Labels: 72h no objection -> merge, Bug Fix, auto-merge

#2407 move code out of $(P ...)
  spec/function.dd
Labels: auto-merge

#2408 Bump currently archived version to v2.081.0
  js/listanchors.js
Labels: auto-merge

#2409 Remove _pre from the v2.081 changelog, s.t. it links to the correct binary
  changelog/2.081.0.dd
Labels: auto-merge

#2411 fix various broken links in articles
  articles/code_coverage.dd
  articles/ctarguments.dd
  articles/exception-safe.dd
  articles/faq.dd
  articles/migrate-to-shared.dd
  articles/mixin.dd
  articles/pretod.dd
  articles/regular-expression.dd
  articles/template-comparison.dd
  articles/templates-revisited.dd
Labels: Bug Fix, Enhancement

#2398 Add a point of contact for security-related issues
  d-security.asc
  dlang.org.ddoc
  dpl-docs/views/layout.dt
  gpg_keys.dd
  posix.mak
  security.dd
Labels: auto-merge

#2417 Mention how to build the documentation with the distro-wide dmd
  CONTRIBUTING.md
Labels: auto-merge

#2400 Fix local Latex PDF build
  spec/latex.ddoc
  spec/lex.dd
Labels: auto-merge

#2419 Fix a few menu links
  dlang.org.ddoc
  dpl-docs/views/layout.dt
Labels: Trivial, auto-merge

#2421 Fix Issue 19055 - [404 Not Found] std.digest.digest
  posix.mak
Labels: Bug Fix, auto-merge

#2420 posix.mak: Only include .di file for DMD documentation
  posix.mak
Labels: auto-merge

#2363 [spec] Add UDAs for parameters
  dlang.org.ddoc
  ebook.ddoc
  spec/attribute.dd
  spec/expression.dd
  spec/function.dd
  spec/latex.ddoc
Labels: auto-merge

#2425 Update Organizations using D for Symmetry
  orgs-using-d.dd
Labels: auto-merge

#2424 betterC section title: add 'features'
  spec/betterc.dd
Labels: Trivial, auto-merge

#2427 Fix SAoC application deadline.
  index.dd
Labels: auto-merge

#2430 Add new donor to sponsors page
  foundation/sponsors.dd
Labels: auto-merge

#2429 Document pragma(mangle) special case on OSX
  spec/pragma.dd
Labels: Spec / content, auto-merge

#2428 Add SAoC banner
  images/symmetry_autumn_of_code.png
  index.dd
Labels: Blocked

#2434 Update donors list.
  foundation/sponsors.dd
Labels: auto-merge
