Repository dlang/dlang.org, pull requests merged in 2018-12, with the labels that each got.

#2518 Update sponsors page
  foundation/sponsors.dd
Labels: auto-merge

#2522 Added example for isStaticFunction
  spec/traits.dd
Labels: Spec / content, auto-merge

#2525 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/2.084.0_pre.dd
  download.dd
Labels: auto-merge

#2526 Remove D1toD2 transition page
  D1toD2.dd
  posix.mak
Labels: auto-merge

#2530 Remove duplicate paragraph for pure fuctions
  spec/function.dd
Labels: Easy Review, auto-merge

#2533 fix DIP25 compilation errors
  spec/function.dd
  spec/struct.dd
Labels: auto-merge

#2535 add initial documentation for issue 19097
  spec/function.dd
Labels: auto-merge

#2517 Update getAliasThis documentation per issue 19439
  spec/traits.dd
Labels: auto-merge
