Repository dlang/dlang.org, pull requests merged in 2018-04, with the labels that each got.

#2303 Remove Amazon smile banner
  images/index-banner.png
  index.dd
Labels: Trivial

#2277 Deprecate class allocators and deallocators
  deprecate.dd
Labels: Vision

#2323 Fix Issue 18702 - FAQ item 'What does D have that C++ doesn't?' comparison link
  articles/faq.dd
Labels: Bug Fix, Trivial, auto-merge

#2321 rewrite struct initialization text
  spec/struct.dd
Labels: Spec / content

#2324 Add SPEC_RUNNABLE_EXAMPLE_FAIL for a postblit example
  spec/struct.dd
Labels: auto-merge

#2326 fix DDOC_AUTO_{PSYMBOL,KEYWORD,PARAM}
  changelog/2.079.0.dd
  dlang.org.ddoc
Labels: Bug Fix

#2027 Clarify deprecation of `scope` as a type constraint
  deprecate.dd
Labels: Spec / content, Vision, auto-merge

#2332 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/2.079.1_pre.dd
  download.dd
Labels: auto-merge

#2333 Update sponsors list
  foundation/sponsors.dd
Labels: auto-merge

#2337 Fix Issue 18747 - [Structs, Unions] example is invalid
  spec/struct.dd
Labels: Bug Fix

#2336 Use $(DPL_DOCS_PATH) variable instead of hard-coding the path
  posix.mak
Labels: Trivial, auto-merge

#2295 download.dd: Add link to OpenSUSE's + Homebrew's project page
  download.dd
Labels: Trivial

#2248 Improve *Foreach over Tuples* spec
  spec/statement.dd
Labels: auto-merge

#2354 make -j fixes - move dependencies down from pseudo-targets
  posix.mak
Labels: Makefiles, auto-merge

#2349 Remove '@' from attributes
  spec/attribute.dd
Labels: auto-merge
