Repository dlang/dlang.org, pull requests merged in 2018-06, with the labels that each got.

#2365 Update deprecated features table. Error for implicit catch statements.
  deprecate.dd
Labels: Trivial, auto-merge

#2374 Fix Issue 18874 - Add thatneedle.com to organizations using D
  images/orgs-using-d/thatneedle.png
  images/orgs-using-d/thatneedle_hq.png
  orgs-using-d.dd
Labels: Enhancement, auto-merge

#2373 Fix Issue 18869 - Add Jumia Food to organizations using D
  images/orgs-using-d/jumiafood.png
  images/orgs-using-d/jumiafood_hq.png
  orgs-using-d.dd
Labels: Enhancement, auto-merge

#2361 Update getLinkage
  spec/traits.dd
Labels: auto-merge

#2385 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/2.080.1.dd
  download.dd
Labels: auto-merge

#2386 Fix Issue 18959 - [Change Log: 2.079.0] substitute was added in std.algorithm.iteration but the changelog points to std.algorithm.searching
  changelog/2.079.0.dd
Labels: Enhancement, auto-merge

#2312 Fix Issue 14099 - Promote run.dlang.io to Resources
  dlang.org.ddoc
Labels: Enhancement, auto-merge

#2113 module.dd: fix a number of minor issues
  spec/module.dd
Labels: Vision

#2388 Discourage use of the `in` storage class
  spec/function.dd
Labels: auto-merge

#2382 Fix Issue 18558 - Template alias spec incomplete
  spec/template.dd
Labels: Bug Fix

#2390 lex.dd: mark undefined and implementation defined behavior
  spec/lex.dd
Labels: auto-merge

#2391 Only include etc & std for the ddox source file list
  posix.mak
Labels: Blocking other work, auto-merge

#2372 [trivial] [deprecate.dd] Fix *Hiding base class functions* wording
  deprecate.dd
Labels: auto-merge

#2396 Add enum member attributes to the spec
  spec/enum.dd
Labels: Spec / content, auto-merge

#2399 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/2.081.0_pre.dd
  download.dd
Labels: auto-merge

#2261 use UNDEFINED_BEHAVIOR macro
  spec/arrays.dd
  spec/attribute.dd
  spec/class.dd
  spec/contracts.dd
  spec/expression.dd
  spec/garbage.dd
  spec/lex.dd
Labels: Spec / content, auto-merge
