Repository dlang/dlang.org, pull requests merged in 2019-01, with the labels that each got.

#2537 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/2.084.0.dd
  download.dd
Labels: auto-merge

#2538 Add ldc-latest-ci to the install script information
  install.dd
Labels: auto-merge

#2539 Add Discord join link to the community section
  dlang.org.ddoc
Labels: auto-merge

#2541 Revert "Add Discord join link to the community section"
  dlang.org.ddoc
Labels: auto-merge

#2545 Update the release schedule for 2019
  changelog/release-schedule.dd
Labels: Trivial

#2453 Document recent -dip1000 changes
  spec/function.dd
  spec/memory-safe-d.dd
Labels: Blocking other work, Spec / content, Vision

#2547 spec/vector.dd: make more formal and complete
  spec/declaration.dd
  spec/expression.dd
  spec/simd.dd
Labels: Spec / content

#2548 add best practice to for statements
  spec/statement.dd
Labels: Easy Review, Spec / content, auto-merge

#2549 Fix syntax formatting
  spec/module.dd
Labels: auto-merge

#2550 Add doc for --DRT-gcopt=cleanup
  spec/garbage.dd
Labels: auto-merge

#2540 Add documentation for Objective-C classes
  spec/class.dd
  spec/function.dd
  spec/objc_interface.dd
Labels: Waiting for DMD PR, auto-merge

#2553 Document precise GC
  spec/garbage.dd
Labels: auto-merge

#2552 Add documentation for Objective-C instance variables
  spec/class.dd
  spec/objc_interface.dd
Labels: Spec / content, auto-merge

#2554 Fix nightly download links
  download.dd
Labels: Trivial

#2557 Bump the stable version of Dub and DMD used to build the DPL docs
  dpl-docs/views/layout.dt
  posix.mak
Labels: Blocking other work, auto-merge

#2556 fix issue 19592 - Rule for IdentifierList is wrong
  spec/declaration.dd
Labels: Bug Fix, auto-merge

#2560 Fix Missing word in OpenCollective instructions
  foundation/donate.dd
Labels: auto-merge

#2562 final switch can be used in -betterC
  spec/betterc.dd
Labels: Easy Review, Spec / content, auto-merge
