Repository dlang/dlang.org, pull requests merged in 2019-12, with the labels that each got.

#2726 Add 'body' to the list of deprecated features
  deprecate.dd
Labels: auto-merge

#2728 Clarification of .min and .max properties of enums
  spec/enum.dd
Labels: Trivial, auto-merge

#2649 add Memory Model and Object Model
  spec/intro.dd
Labels: Spec / content

#2722 Update `@safe` casting rules
  spec/function.dd
Labels: auto-merge
