Repository dlang/dlang.org, pull requests merged in 2019-05, with the labels that each got.

#2635 Introduce term qualifier-convertible
  glossary.dd
  spec/const3.dd
  spec/function.dd
Labels: Spec / content, auto-merge

#2637 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/2.086.0.dd
  download.dd
Labels: auto-merge, stable -> master

#2638 Remove DConf banner
  images/dconf-2019-logo2.png
  index.dd
Labels: auto-merge

#2639 Add LDC to list of snap packages available to download
  download.dd
Labels: auto-merge

#2642 Add a paragraph about default construction
  spec/struct.dd
Labels: auto-merge-squash

#2643 [Trivial] The members don't have to be functions.
  spec/operatoroverloading.dd
Labels: Trivial, auto-merge

#2640 Advance deprecation of class allocators and deallocators: Removal
  deprecate.dd
Labels: auto-merge

#2644 Deprecate scope as a type constraint on class declarations
  deprecate.dd
Labels: auto-merge

#2647 Revert "Add a paragraph about default construction"
  spec/struct.dd
Labels: auto-merge

#2645 Small update to Introduction
  spec/intro.dd
Labels: auto-merge

#2199 Document __traits(isModule) and __traits(isPackage)
  spec/expression.dd
  spec/traits.dd
Labels: auto-merge
