Repository dlang/dlang.org, pull requests merged in 2019-03, with the labels that each got.

#2595 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/2.085.0.dd
  download.dd
Labels: auto-merge

#2594 Update objc documentation to indicate `extern` is required for extern…
  spec/objc_interface.dd
Labels: auto-merge

#2596 Fix changelog entry: -preview -> -revert
  changelog/2.085.0.dd
Labels: Trivial, auto-merge

#2597 update a link to an obsolete wiki page
  spec/ddoc.dd
Labels: auto-merge

#2598 Bump DMD version to 2.085.0
  posix.mak
Labels: auto-merge

#2600 Fixed an issue with list item numbering.
  spec/garbage.dd
Labels: auto-merge

#2601 Change Docker URL from dlanguage/dmd to dlang2/dmd-ubuntu
  download.dd
Labels: auto-merge

#2603 Update memory-safe-d.dd
  spec/memory-safe-d.dd
Labels: auto-merge

#2604 [template.dd] Use better symbol names in examples; add local name alias example
  spec/template.dd
Labels: auto-merge-squash

#2605 Add definition of full expression
  spec/expression.dd
Labels: auto-merge-squash

#2608 [template.dd] Tweak examples
  spec/template.dd
Labels: auto-merge

#2607 Function Default Parameters are underspecified
  spec/function.dd
Labels: Bug Fix

#2609 templates, add the missing form of opaque aggregate declarations
  spec/struct.dd
  spec/template.dd
Labels: auto-merge

#2611 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/2.085.1_pre.dd
  download.dd
Labels: auto-merge

#2613 Add Mercedes-Benz R&D NA to orgs using D
  images/orgs-using-d/mbrdna.png
  orgs-using-d.dd
Labels: auto-merge

#2612 Remove forum server fundraiser
  foundation/donate.dd
Labels: auto-merge

#2561 spec: close a loophole in definition of `@trusted`
  spec/const3.dd
  spec/function.dd
Labels: Bug Fix

#2599 Update struct.dd to highlight copy constructor addition
  spec/struct.dd
Labels: auto-merge

#2615 Update Mercedes-Benz cell in orgs using D
  images/orgs-using-d/mbrdna.png
  orgs-using-d.dd
Labels: auto-merge

#2616 Add dconf 2019 logo, rm 2018 logo
  images/dconf-2019-logo2.png
  images/dconf_logo_2018.png
  index.dd
Labels: auto-merge

#2614 Dimensions and indices are in reverse order.
  spec/arrays.dd
Labels: auto-merge
