Repository dlang/dlang.org, pull requests merged in 2019-08, with the labels that each got.

#2687 Add community Discord join link to the community section
  dlang.org.ddoc
Labels: 72h no objection -> merge, auto-merge

#2691 Minor fix in IsExpression example
  spec/expression.dd
Labels: auto-merge

#2681 Add core.internal.array to module list
  chm-nav.dd
  css/style.css
  dlang.org.ddoc
  dpl-docs/source/ddox_main.d
  posix.mak
  tools/modlist.d
Labels: auto-merge

#2693 Update host compiler to 2.087
  dpl-docs/views/layout.dt
  posix.mak
Labels: auto-merge

#2695 Fix typo on comment
  spec/struct.dd
Labels: Trivial
