Repository dlang/dlang.org, pull requests merged in 2019-02, with the labels that each got.

#2563 Fix AssertExpression link spec/unittest
  spec/unittest.dd
Labels: auto-merge

#2559 Improve TLS-related perf discussion
  articles/migrate-to-shared.dd
Labels: 72h no objection -> merge

#2571 Remove dummy name from the vibe.d example
  index.dd
Labels: auto-merge

#2573 Refactor sponsors page.
  foundation/sponsors.dd
Labels: auto-merge

#2575 Merge remote-tracking branch 'upstream/stable' into merge_stable
  VERSION
  changelog/2.084.1.dd
  download.dd
Labels: auto-merge

#2574 [spec] safe asm statements can be used in safe functions
  spec/function.dd
Labels: Spec / content, auto-merge

#2569 [spec] Remove floating point NCEG operators from spec
  spec/lex.dd
Labels: 72h no objection -> merge

#2579 [spec] Add undocumented macros
  spec/ddoc.dd
Labels: auto-merge

#2580 [spec] Remove typedef from specification
  spec/lex.dd
Labels: auto-merge

#2582 Fixup 2.085.0 changelog
  changelog/2.061.dd
  changelog/2.085.0_pre.dd
  changelog/changelog.ddoc
Labels: Easy Review, auto-merge

#2584 document ref-return-scope function parameters
  spec/function.dd
Labels: Spec / content, Vision

#2586 Replace Flipcause menu with images
  foundation/donate.dd
  images/campaign-forums.png
  images/campaign-general.png
  images/campaign-prman.png
Labels: auto-merge-squash

#2587 Correctly describe PayPal donate button
  foundation/donate.dd
Labels: auto-merge

#2588 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/2.085.0_pre.dd
  download.dd
Labels: auto-merge, stable -> master

#2589 Mark CatchParameter's Identifier as optional
  spec/statement.dd
Labels: auto-merge

#2585 Update Auburn Sounds logo
  images/orgs-using-d/auburn.png
Labels: auto-merge, organizations-page

#2590 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/2.085.0_pre.dd
  download.dd
Labels: auto-merge

#2592 Minor Grammar fix
  CONTRIBUTING.md
Labels: auto-merge
