Repository dlang/dlang.org, pull requests merged in 2019-07, with the labels that each got.

#2673 Spelling.
  orgs-using-d.dd
Labels: auto-merge

#2675 download.dd: Fix local DMD link
  download.dd
Labels: Trivial, auto-merge

#2664 Specify the dotted expressions allowed as iasm operand
  spec/iasm.dd
Labels: Spec / content, auto-merge

#2648 Fix typo in code
  spec/operatoroverloading.dd
Labels: auto-merge

#2677 update example of UDA using the "alias equal traits" syntax
  spec/attribute.dd
Labels: auto-merge

#2678 Fix alphabetic order
  orgs-using-d.dd
Labels: auto-merge

#2676 Deprecate D1 operator overloads
  spec/operatoroverloading.dd
Labels: auto-merge

#2679 Fix Issue 1142 - .stringof performs semantic analysis
  spec/property.dd
Labels: 72h no objection -> merge, Bug Fix

#2683 fix trailing right paren
  spec/traits.dd
Labels: auto-merge

#2682 fix Issue 19402 - specs for promotion rule of shift exp is wrong (without anything else)
  spec/expression.dd
Labels: Bug Fix, auto-merge
