Repository dlang/dlang.org, pull requests merged in 2019-06, with the labels that each got.

#2651 Add a sponsorship button
  .github/FUNDING.yml
Labels: auto-merge

#2652 fix broken link due to macro split on multiple lines
  spec/contracts.dd
Labels: auto-merge

#2653 Remove PR manager campaign from donation page
  foundation/donate.dd
  images/campaign-prman.png
Labels: auto-merge

#2654 Correct imports in example
  spec/garbage.dd
Labels: auto-merge

#2591 Fix confusing grammar in Assignment Overload spec
  spec/struct.dd
Labels: Spec / content, auto-merge-squash

#2663 Add link to uninitializedArray in arrays
  spec/arrays.dd
Labels: auto-merge

#2658 Fixes 19944 - Unit test failures in std.file
  js/run_examples.js
Labels: 72h no objection -> merge, Bug Fix, auto-merge

#2665 Turn on -preview=markdown
  articles/ctod.dd
  articles/d-floating-point.dd
  articles/faq.dd
  articles/intro-to-datetime.dd
  articles/regular-expression.dd
  changelog/2.020.dd
  changelog/2.021.dd
  changelog/2.074.0.dd
  changelog/2.075.1.dd
  changelog/2.078.0.dd
  changelog/2.079.0.dd
  changelog/2.081.0.dd
  changelog/2.082.0.dd
  changelog/2.084.0.dd
  changelog/2.085.0.dd
  changelog/2.086.0.dd
  changelog/index.dd
  dlang.org.ddoc
  download.dd
  ebook.ddoc
  html.ddoc
  plaintext.ddoc
  posix.mak
  rdmd.dd
  spec/latex.ddoc
  verbatim.ddoc
Labels: Ddoc, auto-merge

#2667 Add AID to organisations using D.
  images/orgs-using-d/aid-driving.png
  images/orgs-using-d/aid-driving_hq.png
  orgs-using-d.dd
Labels: auto-merge-squash

#2668 Remove executable flag on image file.
  images/orgs-using-d/netflix_hq.jpg
Labels: auto-merge-squash

#2669 Correct AID hiring link
  orgs-using-d.dd
Labels: auto-merge

#2657 add `__traits(getLocation, symbol)`
  spec/traits.dd
Labels: auto-merge-squash
