Repository dlang/dlang.org, pull requests merged in 2020-06, with the labels that each got.

#2809 [class.dd] Improve long Constructors section and add subsection headings
  spec/class.dd
Labels: auto-merge

#2808 [class.dd] Move Objective-C method specifics to subsection
  spec/class.dd
  spec/function.dd
Labels: auto-merge

#2811 Add permanent links to DIPs
  .htaccess
Labels: auto-merge

#2810 Improve struct constructor docs, add subsections
  spec/class.dd
  spec/struct.dd
Labels: auto-merge

#2813 Improve Nested Classes section
  spec/class.dd
  spec/template.dd
Labels: auto-merge

#2815 Update old dip links from wiki to github
  .htaccess
Labels: auto-merge

#2816 [spec/version.dd] Improve Static If, Static Foreach sections
  spec/version.dd
Labels: auto-merge

#2817 adding keyring hint to the install.sh help page
  install.dd
Labels: auto-merge

#2818 Remove FUNDING.yml
  .github/FUNDING.yml
Labels: Trivial

#2819 update download and changelog for v2.092.1
  VERSION
  changelog/2.092.1.dd
  download.dd
Labels: auto-merge

#2821 move res/ to src/dmd/res
  posix.mak
Labels: Blocking other work

#2823 Remove PDF generation
  CONTRIBUTING.md
  dlang.org.ddoc
  download.dd
  nodatetime.ddoc
  posix.mak
  spec/latex.ddoc
  spec/spec.dd
Labels: auto-merge

#2452 [spec] Document ref and out parameters
  spec/function.dd
Labels: auto-merge

#2454 [spec/function.dd] Add scope parameter section
  spec/function.dd
Labels: auto-merge

#2747 Minor English improvements + notes below
  spec/lex.dd
Labels: auto-merge

#2826 [spec/template.dd] Add see also links & tweaks
  spec/template.dd
Labels: auto-merge

#2829 Document allowed storage classes for ... varargs
  spec/function.dd
Labels: auto-merge
