Repository dlang/dlang.org, pull requests merged in 2020-05, with the labels that each got.

#2783 Add AVR version identifier to documentation
  spec/version.dd
Labels: auto-merge

#2785 Remove reference to -gc compiler switch
  spec/abi.dd
Labels: auto-merge

#2786 spec: add missing version identifiers
  spec/version.dd
Labels: auto-merge

#2784 Add live to AtAttribute
  spec/attribute.dd
Labels: auto-merge

#2789 add methods for dealing with C++ namespaces
  spec/cpp_interface.dd
Labels: Spec / content, auto-merge

#2793 typo
  spec/struct.dd
Labels: auto-merge

#2798 Generate gsoc2013.html
  posix.mak
Labels: auto-merge

#2797 Fix Foundation page title
  foundation/index.dd
Labels: auto-merge

#2787 Add GSOC 2019 to DLF intro
  foundation/about.dd
  foundation/donate.dd
Labels: auto-merge

#2790 Add documentation for @live functions
  spec/ob.dd
  spec/spec.dd
Labels: Enhancement, Spec / content

#2801 Documenting usage on Windows.
  install.dd
Labels: auto-merge

#2802 Explicitly import `core.attribute.selector`
  spec/objc_interface.dd
Labels: auto-merge

#2804 Correctly `call` activate.bat.
  install.dd
Labels: auto-merge

#2799 Remove duplicated release-schedule entry from sitemap
  posix.mak
Labels: auto-merge

#2773 safe interfaces, safe values, safe aliasing
  spec/function.dd
Labels: auto-merge

#2768 function.dd: add notion of safe interface
  spec/function.dd
Labels: Enhancement, Spec / content

#2800 Make ob visible
  posix.mak
  spec/betterc.dd
  spec/ob.dd
  spec/spec.dd
  spec/spec.ddoc
Labels: auto-merge

#2805 Remove travis config
  .travis.yml
Labels: auto-merge

#2791 class allocator receives size_t not uint
  spec/class.dd
Labels: Spec / content, auto-merge

#2806 ob.html: display page contents header
  spec/ob.dd
Labels: auto-merge

#2796 Remove issuestats badge
  README.md
Labels: auto-merge
