Repository dlang/dlang.org, pull requests merged in 2020-02, with the labels that each got.

#2745 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/2.090.1_pre.dd
  download.dd
Labels: auto-merge

#2750 English improvements + sexism fix etc
  articles/const-faq.dd
Labels: auto-merge

#2749 Tiny English improvements + comments...
  spec/declaration.dd
Labels: auto-merge

#2748 Minor English improvements
  spec/module.dd
Labels: auto-merge

#2746 English improvements
  spec/intro.dd
Labels: auto-merge

#2753 Add CRuntime_WASI and WASI versions
  spec/version.dd
Labels: auto-merge

#2727 Clarify signed integer overflow by explicit example.
  spec/expression.dd
Labels: auto-merge-squash

#2756 Clarify 'body' keyword deprecation
  deprecate.dd
Labels: auto-merge

#2757 Add documentation for pragma(crt_{con,de}structor)
  spec/pragma.dd
Labels: auto-merge

#2759 Fix GLINKs in Lambda grammar
  spec/expression.dd
Labels: auto-merge

#2760 document printf format validation
  spec/betterc.dd
  spec/interfaceToC.dd
Labels: Enhancement, Spec / content, Waiting for DMD PR
