Repository dlang/dlang.org, pull requests merged in 2020-01, with the labels that each got.

#2731 hashmap: document that structs automatically generate specialized opEquals/toHash that recurse over fields
  spec/hash-map.dd
Labels: auto-merge

#2732 Fix typo
  spec/type.dd
Labels: auto-merge

#2733 Fix bug in code example
  index.dd
Labels: auto-merge

#2734 Partially revert "Fix bug in code example"
  index.dd
Labels: auto-merge

#2738 install: Update list of supported platforms
  install.dd
Labels: Spec / content, auto-merge

#2739 Fix Issue 20500 - always pass -unittest and --DRT-testmode=run-main
  js/run.js
Labels: Bug Fix, auto-merge

#2741 Bring eponymous template spec in line with implementation
  spec/template.dd
Labels: auto-merge
