Repository dlang/dlang.org, pull requests merged in 2020-11, with the labels that each got.

#2872 Document issue 21340 - `extern(C++, (expression))` now accepts empty tuples
  spec/cpp_interface.dd
Labels: auto-merge-squash

#2873 Rename grammar entities for more descriptive names
  spec/attribute.dd
  spec/declaration.dd
  spec/expression.dd
  spec/function.dd
  spec/iasm.dd
  spec/template-mixin.dd
  spec/template.dd
Labels: auto-merge

#2874 Add CRuntime_Newlib version identifier
  spec/version.dd
Labels: auto-merge

#2876 Fix Issue 21189 - Plain Old Data and copy constructors
  spec/struct.dd
Labels: Bug Fix, auto-merge

#2877 Clarify postblit usage with regards to cpctor
  spec/struct.dd
Labels: auto-merge

#2878 merge stable
  changelog/2.094.2_pre.dd
  download.dd
Labels: auto-merge

#2880 Fix inaccuracy in overload set example
  spec/function.dd
Labels: auto-merge

#2879 spec change for issue 21378 - Allow `pragma(inline, knownAtCTFE);`
  spec/pragma.dd
Labels: auto-merge

#2882 Update Symmetry hiring link in orgs-using-d
  orgs-using-d.dd
Labels: auto-merge, organizations-page

#2840 Improve the wording of struct copy ctor spec.
  spec/struct.dd
Labels: auto-merge

#2883 merge stable
  VERSION
  changelog/2.094.2.dd
  changelog/2.094.2_pre.dd
  download.dd
Labels: auto-merge

#2884 State in language spec that null is a safe value
  spec/function.dd
Labels: auto-merge

#2885 Fix casing/spelling of TargetOS
  ddoc/source/preprocessor.d
Labels: auto-merge
