Repository dlang/dlang.org, pull requests merged in 2020-04, with the labels that each got.

#2769 interfaceToC: fix format string
  spec/interfaceToC.dd
Labels: Bug Fix, Easy Review

#2770 merge stable
  changelog/2.091.1_pre.dd
  download.dd
Labels: auto-merge, stable -> master

#2776 Remove sociomantic from "orgs using D"
  orgs-using-d.dd
Labels: auto-merge

#2778 Spec: getFunctionAttributes now supports `@live`
  spec/traits.dd
Labels: auto-merge

#2777 Spec: Add FuncAttrLive
  spec/abi.dd
Labels: Spec / content, auto-merge

#2779 Fix FuncAttrLive
  spec/abi.dd
Labels: auto-merge

#2781 Add example `__traits(isZeroInit, void))`
  spec/traits.dd
Labels: auto-merge

#2772 document pragma(printf) and pragma(scanf)
  spec/pragma.dd
Labels: Enhancement, Spec / content, auto-merge

#2775 Added missing argument in compile command example
  spec/cpp_interface.dd
Labels: Spec / content, auto-merge

#2767 Updated Homebrew formula link
  download.dd
Labels: auto-merge, links

#2742 replace windbg.exe description with more recent debug options
  dcompiler.dd
  windbg.dd
Labels: Spec / content, auto-merge
