Repository dlang/dlang.org, pull requests merged in 2021-05, with the labels that each got.

#2997 Fix Issue 21869 - Invalid hyperlink to doxygen
  spec/ddoc.dd
Labels: Enhancement

#2998 Fix Issue 21161 - [Variadic Templates] uses outdated example from D1
  articles/variadic-function-templates.dd
Labels: Enhancement

#2999 Issue 19509 - [Conditional Compilation]
  spec/version.dd
Labels: Easy Review

#3004 merge stable
  changelog/2.097.0_pre.dd
  download.dd
Labels: auto-merge

#3007 Fix Issue 21906 - obscure sentence in the introduction to phases of c…
  spec/intro.dd
Labels: Bug Fix, Easy Review

#2959 improve Function Literal section
  spec/expression.dd
Labels: Improve, Spec / content

#3009 [spec/version.dd] fix comma that should be escaped
  spec/version.dd
Labels: Trivial

#3010 Touch up Modules intro.
  spec/module.dd
Labels: auto-merge

#3011 Fix Issue 21935 - Broken Link in Lazy Evaluation Article
  articles/lazy-evaluation.dd
Labels: Bug Fix, Easy Review, auto-merge

#3012 Update IRC channel (from Freenode to Libera.Chat)
  dlang.org.ddoc
  dpl-docs/views/layout.dt
  index.dd
Labels: auto-merge

#3014 fix wording of first sentence in foundation donation paragraph
  foundation/donate.dd
Labels: auto-merge
