Repository dlang/dlang.org, pull requests merged in 2021-09, with the labels that each got.

#3094 ImportC bit fields
  spec/importc.dd
Labels: Spec / content, auto-merge-squash

#3098 treewide: fix duplicate words and typos
  articles/d-floating-point.dd
  articles/hijack.dd
  dstyle.dd
  foundation/donate.dd
  spec/declaration.dd
  spec/expression.dd
  spec/importc.dd
  spec/interfaceToC.dd
Labels: auto-merge

#3105 merge stable
  changelog/2.098.0_pre.dd
  download.dd
Labels: auto-merge, stable -> master
