Repository dlang/dlang.org, pull requests merged in 2021-11, with the labels that each got.

#3117 Fix links
  comparison.dd
Labels: auto-merge

#3119 spec: interfaceToC: remove duplicate ulong type on the table
  articles/ctod.dd
  spec/interfaceToC.dd
Labels: Spec / content, auto-merge

#3118 Update broken examples
  index.dd
Labels: auto-merge

#3122 Add __traits(initSymbol) to the spec
  spec/traits.dd
Labels: auto-merge

#3127 Fix Issue 22544 - [spec] C++ and Objective-C are not single tokens
  spec/attribute.dd
Labels: Bug Fix

#3128 fix ordering of "respectively" for in, out, ref
  spec/function.dd
Labels: auto-merge
