Repository dlang/dlang.org, pull requests merged in 2021-03, with the labels that each got.

#2952 improve Function Contracts section
  spec/function.dd
Labels: Improve, Spec / content

#2939 Improve pragma grammar and links
  spec/pragma.dd
  spec/statement.dd
Labels: Easy Review, auto-merge

#2958 merge Function Literals and Lambda sections
  spec/betterc.dd
  spec/expression.dd
  spec/function.dd
  spec/traits.dd
  spec/type.dd
Labels: Improve, Spec / content

#2961 merge stable
  changelog/2.096.0_pre.dd
  download.dd
Labels: auto-merge

#2964 interface.dd: improve COM section
  spec/interface.dd
Labels: Easy Review, Improve, Spec / content

#2962 type: mostly fix up links
  spec/interface.dd
  spec/type.dd
Labels: Improve, Spec / content

#2967 exorcise the word 'you' from the spec
  spec/arrays.dd
  spec/const3.dd
  spec/cpp_interface.dd
  spec/ddoc.dd
  spec/enum.dd
  spec/expression.dd
  spec/garbage.dd
  spec/interfaceToC.dd
  spec/module.dd
  spec/operatoroverloading.dd
  spec/template.dd
Labels: Easy Review, Spec / content

#2968 spec: Improve declaration syntax section
  spec/declaration.dd
Labels: auto-merge

#2973 move Type grammar from declaration.dd to type.dd
  spec/declaration.dd
  spec/type.dd
Labels: Easy Review, Spec / content

#2977 Spec change for Issue 16140
  spec/statement.dd
Labels: auto-merge

#2979 Fix malformed macro invocation
  articles/variadic-function-templates.dd
Labels: Ddoc, auto-merge

#2980 Typos
  changelog/2.096.0.dd
Labels: Easy Review, Trivial, auto-merge

#2981 fix Issue 21585 - add __traits(totype, string)
  spec/traits.dd
Labels: Enhancement, Spec / content

#2982 Update interfaceToC.dd
  spec/interfaceToC.dd
Labels: auto-merge

#2987 spec/version.dd: Document the D_PIE predefined version
  spec/version.dd
Labels: Easy Review, auto-merge
