Repository dlang/dlang.org, pull requests merged in 2021-12, with the labels that each got.

#3135 Fix Issue 18960 - Function parameter requires name with default value
  spec/declaration.dd
Labels: Bug Fix

#3124 spec: abi: add function-local parent symbols to the mangling grammar
  spec/abi.dd
Labels: Spec / content, auto-merge, ABI

#3137 Revert "Fix Issue 22518 - return without scope/ref not specified"
  spec/function.dd
Labels: auto-merge

#3141 merge stable
  changelog/2.098.1_pre.dd
  download.dd
  spec/abi.dd
Labels: auto-merge

#3140 fix Issue 22527 - Casting out-of-range floating point value to signed…
  spec/expression.dd
Labels: Bug Fix

#3139 fix Issue 19136 - is expressions don't work as documented
  spec/expression.dd
Labels: Bug Fix

#3142 Deprecate complex number keywords
  spec/lex.dd
Labels: auto-merge

#3144 Fix Issue 22363 - Wrong link in https://dlang.org/spec/abi.html for "…
  spec/abi.dd
Labels: Bug Fix

#3146 merge stable
  VERSION
  changelog/2.098.1.dd
  download.dd
Labels: auto-merge

#3147 Use an Oxford comma in the allMembers spec
  spec/traits.dd
Labels: auto-merge

#3152 Fix Issue 22504 - spec/type.html: 6.1 Basic Data Types: Backslash missing in default value for {,d,w}char
  spec/type.dd
Labels: auto-merge, Bug Fix

#3154 Document __traits(isTemplate) + overload set
  spec/traits.dd
Labels: auto-merge
