Repository dlang/dlang.org, pull requests merged in 2022-07, with the labels that each got.

#3329 add Associated C Compiler to glossary
  glossary.dd
Labels: Spec / content, Easy Review

#3328 update ImportC introduction
  spec/importc.dd
Labels: Spec / content, Easy Review

#3330 expand on preprocessor section
  spec/importc.dd
Labels: Spec / content, Easy Review

#3331 ImportC: add quick examples
  spec/importc.dd
Labels: Spec / content, Easy Review

#3335 merge stable
  VERSION
  changelog/2.100.1.dd
  download.dd
Labels: auto-merge

#3337 Fix build script paths to work with new merged repository structure
  .circleci/run.sh
  posix.mak
Labels: auto-merge

#3338 Update docs to not allow `scope(failure)` exit with a return
  spec/statement.dd
Labels: auto-merge

#3336 [spec/expression] Improve FunctionLiteral type inference docs
  spec/expression.dd
Labels: auto-merge

#3340 adjustments to ImportC documentation
  spec/importc.dd
Labels: Spec / content, auto-merge, Easy Review

#3341 Fix Issue 17514 - "positive" -> "nonnegative"
  spec/attribute.dd
Labels: auto-merge, Bug Fix

#3342 Fix Issue 17324 - Floating point 1/(1/x) > 0 if x > 0 not generally true
  articles/d-floating-point.dd
Labels: auto-merge, Bug Fix

#3344 Fix download links
  download.dd
Labels: auto-merge

#3345 Fix Issue 17623 - Unexpected failure of an assertion on empty strings
  spec/expression.dd
Labels: Bug Fix

#3346 Fix Issue 19036 - .tupleof order guarantee
  spec/class.dd
Labels: Enhancement

#3347 Fix Issue 18887 - inout badly described
  spec/const3.dd
  spec/function.dd
Labels: auto-merge, Bug Fix

#3348 Fix issue 23237 - temp force 2.100.0 download
  download.dd
Labels: Bug Fix

#3352 Fix Issue 22835 - Undocumented type specializations of isExpression
  spec/expression.dd
Labels: Bug Fix

#3355 [spec/struct] Add 'Union Literals' & 'Anonymous Structs & Unions'
  spec/struct.dd
Labels: Bug Fix

#3354 Fix Issue 15379 - "final" attribute on function parameter
  spec/function.dd
Labels: auto-merge, Bug Fix
