Repository dlang/dlang.org, pull requests merged in 2022-09, with the labels that each got.

#3401 [spec/expression] Improve FunctionLiteral docs
  spec/expression.dd
Labels: auto-merge

#3319 Fix 23186 - wchar/dchar do not have their endianess defined
  spec/abi.dd
  spec/type.dd
Labels: Enhancement, auto-merge

#3405 Fix issue 23314 - Language spec falsely states that struct field inva…
  spec/struct.dd
Labels: auto-merge, Bug Fix

#3402 Fix 23194 - Add ucora to orgs using d
  images/orgs-using-d/ucora.svg
  orgs-using-d.dd
Labels: Bug Fix

#3403 [spec/arrays] Improve resizing section
  spec/arrays.dd
Labels: auto-merge

#3404 [spec/arrays] Improve assignment docs
  spec/arrays.dd
Labels: auto-merge, Bug Fix

#3406 [spec/class] Tweak alias this docs
  spec/class.dd
Labels: auto-merge

#3379 [spec/type] Add Value Range Propagation section
  spec/type.dd
Labels: auto-merge, Bug Fix

#3407 merge stable
  VERSION
  changelog/2.100.2.dd
  download.dd
Labels: auto-merge

#3353 Revert download and changelog version changes
  download.dd
  index.dd
Labels: auto-merge

#3408 Github -> GitHub
  foundation/sponsors.dd
  orgs-using-d.dd
Labels: auto-merge

#3409 Corrected a grammatical error
  spec/struct.dd
Labels: auto-merge

#3415 [spec/type] Document that constant variables can track value range
  spec/type.dd
Labels: auto-merge

#3413 Fix 23359 - Rename InOut to ParameterStorageClass
  spec/function.dd
Labels: Enhancement

#3411 Angle brackets are seen by browsers as HTML
  spec/importc.dd
Labels: auto-merge

#3410 Allow lambdas to return auto ref
  spec/expression.dd
Labels: auto-merge

#3417 [spec] Fix closure allocation docs
  spec/function.dd
Labels: auto-merge

#3416 Fix slice to static array implicit conversion docs
  spec/expression.dd
Labels: auto-merge

#3418 [spec] Document NewExpression forms
  spec/expression.dd
Labels: auto-merge

#3356 Fix Issue 22141 - Property .capacity is not listed in the array prope…
  spec/arrays.dd
Labels: Enhancement
