Repository dlang/dlang.org, pull requests merged in 2022-02, with the labels that each got.

#3184 [spec/function.dd] Improve *Virtual Functions* section
  spec/attribute.dd
  spec/function.dd
Labels: auto-merge

#3196 Update DIP links
  .htaccess
Labels: Trivial

#3206 changelog/next_version.sh: Zero-pad three-digit version properly
  changelog/next_version.sh
Labels: auto-merge

#3208 Disambiguate 'Mixins' everywhere
  articles/index.dd
  articles/mixin.dd
  articles/template-comparison.dd
  comparison.dd
  dlang.org.ddoc
Labels: auto-merge

#3212 fix Issue 22305 - ImportC: #pragma STDC FENV_ACCESS is not supported
  spec/importc.dd
Labels: Spec / content, Bug Fix

#3197 Correct hasMember trait example
  spec/traits.dd
Labels: auto-merge

#3214 add Iain Buclaw to GPG keyring
  d-keyring.gpg
  gpg_keys.dd
Labels: auto-merge

#3216 ddoc_preprocessor: Don't execute dmd twice
  ddoc/source/preprocessor.d
Labels: auto-merge

#3218 Fix issue 15437 - documentation for typeof(someTemplate) == void
  spec/type.dd
Labels: auto-merge, Bug Fix

#3219 merge stable
  changelog/2.099.0_pre.dd
  download.dd
Labels: auto-merge

#3220 spec: Remove mentions of custom allocators and deallocators
  deprecate.dd
  spec/class.dd
  spec/expression.dd
  spec/module.dd
Labels: auto-merge

#3182 ImportC: add documentation for __import
  spec/importc.dd
Labels: Enhancement, auto-merge

#3183 [spec/template.dd] Add *Template Parameters* heading
  spec/template.dd
Labels: auto-merge

#3210 [index.dd] Tweak character pair frequency example
  index.dd
Labels: auto-merge

#3203 [spec/statement.dd] Improve foreach docs
  spec/statement.dd
Labels: auto-merge

#3224 Sign the new d-keyring.gpg file
  d-keyring.gpg.sig
Labels: auto-merge

#3150 [spec] `main` can be declared with `auto` or `noreturn`
  spec/function.dd
Labels: auto-merge

#3226 assert_writeln_magic.d: Bump libdparse to 0.19.0
  ddoc/source/assert_writeln_magic.d
Labels: auto-merge

#3228 Fix broken DDSUBLINKs & code_coverage DDLINK
  articles/ctarguments.dd
  spec/arrays.dd
  spec/attribute.dd
  spec/contracts.dd
  spec/expression.dd
  spec/function.dd
  spec/hash-map.dd
  spec/simd.dd
  spec/template.dd
  spec/traits.dd
  spec/type.dd
  spec/version.dd
Labels: auto-merge

#3229 book: Remove timestamps when building with DIFFABLE=1
  book/build.d
Labels: auto-merge

#3230 annotate opApply() delegates with scope
  spec/statement.dd
Labels: Spec / content, auto-merge, Easy Review

#3233 Fix issue 22795 - Access denied when trying to download DMD 2.099.0-b…
  download.dd
Labels: auto-merge, Bug Fix
