Repository dlang/dlang.org, pull requests merged in 2022-08, with the labels that each got.

#3358 Simplify AA pair example
  spec/hash-map.dd
Labels: auto-merge

#3360 Fix Issue 22237 - AA.update is underspecified
  spec/hash-map.dd
Labels: auto-merge

#3362 Fix inout link
  spec/function.dd
Labels: auto-merge

#3364 Changed the "here" link in Predefined Macros
  spec/ddoc.dd
Labels: auto-merge

#3366 DConf is over
  index.dd
Labels: auto-merge

#3369 Fix Issue 23276 - DOC: &gt; instead of > in dmd-windows.html
  dcompiler.dd
Labels: Enhancement, auto-merge

#3365 [spec/ddoc] Improve macro expansion section
  spec/ddoc.dd
Labels: Bug Fix

#3359 Fix AA word count example
  spec/hash-map.dd
Labels: auto-merge

#3372 Update word count examples
  spec/hash-map.dd
  wc.dd
Labels: auto-merge

#3371 [spec/expression] Tweak examples
  spec/expression.dd
Labels: auto-merge

#3370 Follow-up for PR #3357
  spec/expression.dd
Labels: auto-merge

#3378 [spec/type] Add example for integer promotion
  spec/type.dd
Labels: auto-merge

#3380 Bump archive version to v2.099.0
  js/listanchors.js
Labels: auto-merge

#3374 [spec/type] Improve Type Conversions section
  spec/function.dd
  spec/type.dd
Labels: auto-merge

#3377 [spec/expression] Improve docs for `this` and `super`
  spec/expression.dd
  spec/function.dd
Labels: auto-merge

#3382 [spec/expression] Tweak CmpExpression docs
  spec/expression.dd
Labels: auto-merge

#3383 [spec/type] Tweak introduction
  spec/type.dd
Labels: auto-merge

#3385 Fix Issue 18496 - Complement expressions now actually int promote
  spec/expression.dd
Labels: auto-merge, Bug Fix

#3388 [spec/expression] Tweak increment/decrement ops
  spec/expression.dd
Labels: auto-merge

#3386 [spec/expression] Document `.` postfix operator
  spec/expression.dd
Labels: auto-merge

#3373 Fix Issue 21279 - cast expression between integer types is not defined
  spec/expression.dd
Labels: auto-merge, Bug Fix

#3381 [spec/type] Improve numeric type conversion examples
  spec/expression.dd
  spec/type.dd
Labels: auto-merge

#3391 Fix link to “Invariant Strings” article
  articles/const-faq.dd
Labels: auto-merge

#3390 add Cheat Sheet for RefScopeReturn
  spec/function.dd
Labels: Spec / content

#3396 update ref return scope
  spec/function.dd
Labels: Spec / content

#3395 [spec/expression] Improve Lvalue section
  spec/expression.dd
Labels: auto-merge

#3393 [spec/expression] Tweak examples
  spec/expression.dd
Labels: auto-merge

#3398 update download and changelog for v2.100.2-beta.1
  changelog/2.100.2_pre.dd
  download.dd
Labels: auto-merge

#3392 Deprecate throwing from contracts of nothrow functions
  deprecate.dd
Labels: auto-merge

#3400 fix formatting mistake
  spec/function.dd
Labels: Spec / content, auto-merge

#3389 [spec] Move main pointer docs to type.dd from arrays.dd
  spec/arrays.dd
  spec/attribute.dd
  spec/expression.dd
  spec/type.dd
Labels: auto-merge

#3387 [spec/expression] Improve index and slice docs
  spec/expression.dd
Labels: auto-merge-squash

#3384 [spec/struct] Improve union init & anonymous docs
  spec/struct.dd
Labels: auto-merge-squash

#3394 [spec/expression] Improve AssignExpression docs
  spec/expression.dd
Labels: auto-merge
