Repository dlang/dlang.org, pull requests merged in 2022-01, with the labels that each got.

#3161 [spec] Improve array docs
  spec/arrays.dd
  spec/expression.dd
  spec/hash-map.dd
Labels: auto-merge

#3155 [expression.dd] Improve formatting for *Definitions and Terms*
  spec/expression.dd
Labels: auto-merge

#3156 [expression.dd] Improve formatting for comparison operators
  spec/expression.dd
Labels: auto-merge

#3166 [statement.dd] Improve docs & examples
  spec/statement.dd
Labels: auto-merge

#3167 [spec] Make more examples runnable
  spec/class.dd
  spec/declaration.dd
  spec/function.dd
  spec/operatoroverloading.dd
  spec/template.dd
Labels: auto-merge

#3151 [module.dd] Use relevant subheadings
  spec/module.dd
Labels: auto-merge

#3174 [spec] Fix 'gc' typo
  spec/class.dd
  spec/garbage.dd
Labels: Trivial, auto-merge

#3175 [spec/statement.dd] Remove some unnecessary GLINKs
  spec/statement.dd
Labels: auto-merge

#3176 Follow-up to DMD PR#14892: document version(D_ProfileGC).
  spec/version.dd
Labels: auto-merge

#3178 [spec/statement.dd] Remove more unnecessary GLINKs
  spec/statement.dd
Labels: auto-merge

#3181 Remove underground rekordz as the link now seems to point to a drug c…
  orgs-using-d.dd
Labels: Enhancement

#3186 [spec/template.dd] Tweak 'This Parameter' examples
  spec/template.dd
Labels: auto-merge

#3158 [expression.dd] Improve *CastExpression* docs
  spec/expression.dd
Labels: auto-merge

#3149 [spec] Document `noreturn`
  spec/importc.dd
  spec/type.dd
Labels: auto-merge

#3163 [arrays.dd] Improve pointer docs
  spec/arrays.dd
  spec/expression.dd
Labels: auto-merge

#3160 [expression.dd] Improve IndexExpression & SliceExpression docs
  spec/expression.dd
Labels: auto-merge

#3168 [statement.dd] Tweak ForStatement docs
  spec/statement.dd
Labels: auto-merge

#3179 [spec/statement.dd] Improve switch docs
  spec/statement.dd
Labels: auto-merge

#3188 ImportC: add EnumBaseType to enums
  spec/importc.dd
Labels: Enhancement

#3191 typo: crt_destructor->crt_constructor
  spec/pragma.dd
Labels: auto-merge

#3193 remove Alt grammar rules
  spec/declaration.dd
Labels: Easy Review

#3195 Fix issue 22711 - Effect of template UDAs on instance members is undo…
  spec/attribute.dd
Labels: Bug Fix

#3164 Replace throw statement with throw expressions (DIP 1034)
  articles/lazy-evaluation.dd
  spec/expression.dd
  spec/statement.dd
Labels: auto-merge-squash

#3198 add contracts to ShortenedFunctionBody grammar
  spec/function.dd
Labels: auto-merge
