Repository dlang/dlang.org, pull requests merged in 2022-05, with the labels that each got.

#3291 merge stable
  changelog/2.100.0_pre.dd
  download.dd
Labels: auto-merge

#3279 Document ImportC support for typeof operator
  spec/importc.dd
Labels: auto-merge, Waiting for DMD PR

#3292 Update release schedule for 2022
  changelog/release-schedule.dd
Labels: auto-merge

#3293 clarify return-ref combined with scope parameters
  spec/function.dd
Labels: Spec / content, Improve

#3296 Fix link to DIP1038
  changelog/2.100.0.dd
Labels: auto-merge

#3304 Add dconf info to front page
  images/dconf22-logo.jpg
  index.dd
Labels: auto-merge

#3301 minor changes to undefined behavior notes
  spec/arrays.dd
  spec/const3.dd
  spec/declaration.dd
  spec/function.dd
  spec/lex.dd
  spec/statement.dd
Labels: Spec / content, Improve, Easy Review

#3309 [spec/attribute] Use static data in example
  spec/attribute.dd
Labels: auto-merge

#3308 [spec/attribute] Mention static on nested types
  spec/attribute.dd
Labels: auto-merge

#3306 [spec/struct] Improve introduction section
  spec/struct.dd
Labels: auto-merge

#3305 [spec/class.dd] Move abstract class docs to class.dd & add examples
  spec/attribute.dd
  spec/class.dd
Labels: auto-merge

#3299 [spec/function] Improve UFCS docs
  spec/function.dd
Labels: auto-merge

#3310 [spec/class] Improve list of class components
  spec/class.dd
Labels: auto-merge

#3313 [spec] Tweak function literal docs
  spec/expression.dd
  spec/function.dd
Labels: auto-merge

#3311 [spec/function] Improve function body docs
  spec/function.dd
Labels: auto-merge
