Repository dlang/dlang.org, pull requests merged in 2022-03, with the labels that each got.

#3157 [spec/expression.dd] Improve InExpression
  spec/expression.dd
  spec/operatoroverloading.dd
Labels: auto-merge

#3177 [spec/template.dd] Improve template instantiation docs
  spec/template.dd
Labels: auto-merge

#3187 [spec/interface.dd] Tweak interface docs
  spec/interface.dd
Labels: auto-merge

#3189 [spec/statement.dd] Tweak switch/case docs
  spec/statement.dd
Labels: auto-merge

#3236 merge stable
  changelog/2.099.0_pre.dd
  download.dd
Labels: auto-merge

#3194 [spec/statement.dd] Improve 'Foreach over Sequences' docs
  spec/statement.dd
Labels: auto-merge

#3199 [spec/statement.dd] Improve 'Foreach over Associative Arrays'
  spec/statement.dd
Labels: auto-merge

#3202 [spec/statement.dd] Improve 'Foreach over Arrays'
  spec/statement.dd
Labels: auto-merge

#3232 [spec] Improve concatenation docs
  spec/arrays.dd
  spec/expression.dd
Labels: auto-merge

#3223 [spec/function.dd] Improve Pure Functions section
  spec/function.dd
Labels: auto-merge

#3217 [spec/struct.dd] Improve struct initialization docs
  spec/declaration.dd
  spec/struct.dd
Labels: auto-merge-squash

#3205 [spec/statement.dd] Improve foreach loop invariant docs
  spec/statement.dd
Labels: auto-merge-squash

#3239 [spec/traits.dd] Fix wrong uses of 'tuple'
  spec/traits.dd
Labels: auto-merge

#3169 [prman.dd] [intro.dd] [spec.ddoc] Few small fix.
  foundation/prman.dd
  spec/intro.dd
  spec/spec.ddoc
Labels: Bug Fix, auto-merge-squash

#3192 [spec/statement.dd] Improve opApply docs
  spec/statement.dd
Labels: auto-merge

#3076 specify @trusted functions must have @safe interface
  spec/memory-safe-d.dd
Labels: Spec / content, auto-merge, Easy Review

#3100 Add Contracts versions
  spec/version.dd
Labels: auto-merge

#3031 ImportC: add tag symbol section
  spec/importc.dd
Labels: Spec / content

#3240 Deprecate body keyword
  deprecate.dd
  spec/lex.dd
Labels: auto-merge

#3241 set error and removal date for delete’s deprecation
  deprecate.dd
Labels: auto-merge

#3242 Fix deprecated of body keyword
  spec/lex.dd
Labels: auto-merge

#3243 fix issue 22850 - [Oh No! Page Not Found] Contract Programming
  articles/cppcontracts.dd
Labels: auto-merge, Bug Fix

#3244 spec/lex.dd: Remove HexString from grammar
  spec/lex.dd
Labels: Easy Review

#3246 Fix issue 22215 - returning expired stack pointers in `@system` code …
  spec/memory-safe-d.dd
Labels: Bug Fix

#3247 deprecate.dd: Add cent/ucent to the deprecation table
  deprecate.dd
  spec/lex.dd
  spec/type.dd
Labels: auto-merge

#3248 merge stable
  VERSION
  changelog/2.099.0.dd
  download.dd
Labels: auto-merge

#3225 [spec/template.dd] Improve TemplateSequenceParameter docs
  spec/template.dd
  spec/type.dd
Labels: auto-merge

#3215 Move ArrayInitializer grammar to expression.dd & improve docs
  spec/declaration.dd
  spec/expression.dd
Labels: auto-merge

#3253 Update year in platform-downloads.js
  js/platform-downloads.js
Labels: auto-merge

#3254 spec/traits.dd: put traits under correct headings
  spec/traits.dd
Labels: auto-merge

#3252 merge stable
  .circleci/run.sh
  download.dd
Labels: auto-merge

#3121 spec/abi.dd: ELF and Mach-O targets now use DWARF EH
  spec/abi.dd
Labels: Spec / content, auto-merge

#3235 [spec/expression.dd] Improve IsExpression docs
  css/style.css
  spec/expression.dd
Labels: auto-merge

#3258 spec/iasm.dd: Move GCC syntax to the bottom of the page
  spec/iasm.dd
Labels: Easy Review

#3259 Fix issue 22027 - `inout` doesn't imply return
  spec/function.dd
Labels: Enhancement

#3264 Add version condition invariants
  spec/version.dd
Labels: auto-merge, Waiting for DMD PR

#3265 deprecate: make unannotated asm blocks error instead of deprecation
  deprecate.dd
Labels: auto-merge, Waiting for DMD PR
