Repository dlang/dlang.org, pull requests merged in 2022-10, with the labels that each got.

#3421 [spec] Tweak template alias parameter docs
  spec/template.dd
Labels: auto-merge

#3420 Fix scope class link
  spec/class.dd
Labels: auto-merge

#3426 [trivial] [spec/function] Tweak attribute inference docs
  spec/function.dd
Labels: auto-merge

#3428 posix.mak: Fix make clean recipe
  posix.mak
Labels: Easy Review

#3429 Use downloads.dlang.org for all main download links
  download.dd
  js/platform-downloads.js
Labels: Trivial, auto-merge

#3430 Update changelog and downloads links to use https
  changelog/changelog.ddoc
  changelog/prerelease.ddoc
  download.dd
Labels: auto-merge, Easy Review

#3434 Update CircleCI image
  .circleci/config.yml
Labels: auto-merge, Continuous Integration

#3436 merge stable
  .circleci/config.yml
  changelog/2.101.0_pre.dd
  download.dd
Labels: auto-merge

#3422 [spec] List symbols which can be aliased
  spec/declaration.dd
Labels: auto-merge

#3425 [spec/template] Move Type Parameters above Type Parameter Deduction
  spec/template.dd
Labels: auto-merge

#3438 Fix counts in changelog for v2.101.0-beta.1
  changelog/2.101.0_pre.dd
Labels: stable -> master

#3439 Fix Issue 23426 - Example Run button shows wrong line numbers for errors
  js/run.js
  js/run_examples.js
Labels: Enhancement, auto-merge

#3441 pattern matching for Is Expressions
  spec/expression.dd
Labels: Spec / content, Ddoc, Easy Review

#3440 Template type specialization and pattern matching
  spec/template.dd
Labels: Spec / content, Ddoc, Easy Review

#3433 circleci: Migrate to circleci convenience images
  .circleci/config.yml
Labels: auto-merge, Easy Review, Continuous Integration

#3447 Fix 23436 - Spec falsely states mutable references in struct .init ar…
  spec/struct.dd
Labels: Bug Fix

#3445 [spec/arrays] Improve capacity docs
  spec/arrays.dd
Labels: Enhancement, auto-merge

#3427 Clarify requirements for struct copy constructors
  spec/struct.dd
Labels: auto-merge, Bug Fix

#3449 document vector support for == != < <= > >=
  spec/simd.dd
Labels: Spec / content
