Repository dlang/dlang.org, pull requests merged in 2022-04, with the labels that each got.

#3266 Fix 22959 - Extend documentation for C/D main functions.
  spec/function.dd
Labels: Spec / content, auto-merge, Bug Fix

#3263 Spec changes for static array .tupleof
  spec/arrays.dd
Labels: Waiting for DMD PR

#3272 [spec/class] Improve tupleof docs
  spec/class.dd
  spec/struct.dd
Labels: auto-merge

#3273 [spec/statement] Tweak foreach sequence docs
  spec/statement.dd
Labels: auto-merge

#3201 Add @mustuse (DIP 1038) to the language spec
  spec/attribute.dd
Labels: Blocked, Spec / content, auto-merge

#3271 spec/arrays: Improve static array .tupleof docs
  spec/arrays.dd
  spec/template.dd
Labels: auto-merge-squash

#3227 assert_writeln_magic: Report filename on error (instead of `magic.d`)
  ddoc/source/assert_writeln_magic.d
  ddoc/source/preprocessor.d
  dpl-docs/source/ddox_main.d
Labels: 72h no objection -> merge

#3276 [spec/attribute] Document `final` attribute
  spec/attribute.dd
  spec/class.dd
  spec/function.dd
Labels: auto-merge

#3278 Fix issue 22503 - Invalid changelog entry for isValidCodePoint
  changelog/2.098.0.dd
Labels: Trivial, auto-merge, Bug Fix

#3281 Add extern(C++, class) and extern(C++, struct) to grammar
  spec/attribute.dd
Labels: auto-merge

#3282 Update DIP links
  .htaccess
Labels: Trivial, auto-merge

#3277 [spec] Improve @disable docs
  spec/attribute.dd
  spec/struct.dd
Labels: auto-merge

#3286 Fix issue 23062 - Function/delegate inference example does not compile
  spec/expression.dd
Labels: auto-merge, Bug Fix

#3287 Mention scope attributes on class `this`
  spec/class.dd
Labels: auto-merge

#2578 Clarify what happens with overlarge shifts
  spec/expression.dd
Labels: auto-merge

#3288 Fixup `scope` attribute documentation
  spec/attribute.dd
Labels: auto-merge
