Repository dlang/dlang.org, pull requests merged in 2022-12, with the labels that each got.

#3458 Fix 23541 - [ImportC] dlang.org contains incorrect links
  spec/importc.dd
Labels: Bug Fix

#3462 Fix Issue 23511 - Incrementing a not supported type in enum
  spec/enum.dd
Labels: auto-merge, Bug Fix

#3461 Improve union docs
  spec/struct.dd
Labels: auto-merge

#3469 Plan release schedule for 2023
  changelog/release-schedule.dd
Labels: Release Schedule

#3468 [operatoroverloading.dd] move Array2D example down
  spec/operatoroverloading.dd
Labels: auto-merge

#3464 document ModuleInfo
  spec/abi.dd
  spec/betterc.dd
  spec/ddoc.dd
  spec/version.dd
Labels: Spec / content

#3473 update download and changelog for v2.101.1
  VERSION
  changelog/2.101.1.dd
Labels: auto-merge, stable -> master

#3466 add spec/windows.dd
  spec/ob.dd
  spec/spec.dd
  spec/windows.dd
Labels: Spec / content

#3474 Fix Issue 23553 - opCmp spec is incomplete
  spec/operatoroverloading.dd
Labels: Enhancement

#3475 Remove version(integer) from docs
  spec/version.dd
Labels: auto-merge

#3477 windows.html was not being built
  posix.mak
  spec/spec.dd
Labels: Trivial, Spec / content

#3443 Fix Issue 23467 - `tools/dspec_tester.d` calls `readText` multiple times per file
  tools/dspec_tester.d
Labels: Enhancement, auto-merge
