Repository dlang/dlang.org, pull requests merged in 2023-06, with the labels that each got.

#3624 fix Issue 23697 - No examples of invalid forward references in C code…
  spec/importc.dd
Labels: Spec / content, Bug Fix, Easy Review

#3626 update download and changelog for v2.104.0
  VERSION
  changelog/2.104.0.dd
  download.dd
Labels: auto-merge

#3628 Add article on building Windows DLLs
  articles/RefReturnScope.dd
  articles/dll-windows.dd
  articles/index.dd
  book/dlang.org.ddoc
  css/style.css
  dlang.org.ddoc
  posix.mak
Labels: Spec / content

#3631 Link to Bartosz Milewski's blog
  spec/ob.dd
Labels: Spec / content

#3622 fix Issue 23692 - ImportC: __pragma and __declspec are not documented…
  spec/importc.dd
Labels: Spec / content, Bug Fix

#3634 spec/betterc.dd: Fix link to ModuleInfo
  spec/betterc.dd
Labels: Trivial

#3629 clarify difference between declaration and definition
  spec/attribute.dd
Labels: Spec / content, Easy Review

#3636 Fix Issue 23946 - spec states "there can only be one destructor"
  spec/class.dd
  spec/template-mixin.dd
Labels: Bug Fix

#3640 update download and changelog for v2.104.1-beta.1
  changelog/2.104.1_pre.dd
  download.dd
Labels: stable -> master

#3641 add reference to DLL best practices
  articles/dll-windows.dd
Labels: Easy Review

#3648 scope does not affect operator overloading
  spec/function.dd
Labels: Spec / content

#3642 [spec/lex] Improve floating point docs
  spec/lex.dd
Labels: Enhancement

#3476 [spec] Disallow throwing qualified objects
  spec/expression.dd
Labels: auto-merge
