Repository dlang/dlang.org, pull requests merged in 2023-05, with the labels that each got.

#3594 Fix issue 23872 - Wrong example in Interfacing to C, calling `printf`
  spec/interfaceToC.dd
Labels: Bug Fix

#3496 Parallelism fixes
  posix.mak
  tools/chmgen.d
Labels: auto-merge

#3597 update download and changelog for v2.104.0-beta.1
  changelog/2.104.0_pre.dd
  download.dd
Labels: stable -> master

#3601 Correction
  spec/lex.dd
Labels: auto-merge

#3600 [spec] Tweak function docs
  spec/expression.dd
  spec/function.dd
  spec/template.dd
Labels: auto-merge

#3599 [spec/function] Tweak delegate docs
  spec/function.dd
Labels: auto-merge

#3589 Allow `alias this` to use assignment-style syntax
  spec/struct.dd
Labels: Waiting for DMD PR

#3603 Change grammar to allow builtin types as UDAs in parens
  spec/attribute.dd
Labels: auto-merge

#3606 update download and changelog for v2.104.0-rc.1
  changelog/2.104.0_pre.dd
  download.dd
Labels: auto-merge, stable -> master

#3609 add ACC macro for Associated C Compiler
  dlang.org.ddoc
  spec/importc.dd
  spec/windows.dd
Labels: Spec / content

#3611 add article on ref, return, and scope annotations
  articles/RefReturnScope.dd
  articles/index.dd
  posix.mak
Labels: Spec / content, auto-merge

#3617 Add Ahrefs to orgs page
  images/orgs-using-d/ahrefs.svg
  orgs-using-d.dd
Labels: auto-merge

#3605 Specify that nested static struct might also be POD
  spec/struct.dd
Labels: auto-merge
