Repository dlang/dlang.org, pull requests merged in 2023-07, with the labels that each got.

#3651 update download and changelog for v2.104.1
  VERSION
  changelog/2.104.1.dd
  changelog/2.104.1_pre.dd
  download.dd
Labels: stable -> master

#3655 add spec/legacy page
  spec/glossary.dd
  spec/legacy.dd
  spec/spec.dd
  spec/spec.ddoc
Labels: Spec / content, Easy Review

#3656 [spec/enum] Tweak docs
  spec/enum.dd
Labels: Enhancement

#3659 add body legacy code
  deprecate.dd
  spec/legacy.dd
Labels: Spec / content, Easy Review

#3619 [spec/function] Improve `return` struct method attribute docs
  spec/function.dd
Labels: Enhancement, Bug Fix

#3662 [spec] Improve string literal docs
  spec/expression.dd
  spec/lex.dd
Labels: Bug Fix

#3664 update download and changelog for v2.104.2
  VERSION
  changelog/2.104.2.dd
Labels: stable -> master

#3663 [spec] `assert` argument is converted to bool
  spec/expression.dd
Labels: Spec / content, auto-merge

#3647 Fix Issue 24012 - [spec/cpp_interface] _d_dynamicArray generated by -…
  spec/cpp_interface.dd
Labels: Enhancement, Spec / content, auto-merge

#3672 [trivial] Use PANEL for note about C++ class syntax
  spec/class.dd
Labels: Trivial
