Repository dlang/dlang.org, pull requests merged in 2023-02, with the labels that each got.

#3514 update download and changelog for v2.102.0
  VERSION
  changelog/2.102.0.dd
  download.dd
Labels: auto-merge

#3513 Fixed issue 22348 - Specify forward referencing of MixinDeclaration
  spec/module.dd
Labels: Bug Fix

#3517 Fix issue 11493 - Correctly explain code snippet behaviour
  spec/type.dd
Labels: Bug Fix

#3516 Fix issue 16707
  spec/template.dd
Labels: Bug Fix

#3515 Fixed issue 18830 - document "new" with "scope" in @nogc Functions
  spec/function.dd
Labels: Bug Fix, auto-merge-squash

#3519 Fix Issue 22594 - Update Interfacing to C to include intptr_t and uin…
  spec/interfaceToC.dd
Labels: Enhancement, auto-merge

#3512 Fix Issue 21178 - It is not explained what is "unknown"
  spec/enum.dd
Labels: Bug Fix

#3470 `extern(C++)` classes have no base class unless specified
  spec/expression.dd
Labels: auto-merge

#3521 Fix typo from previous commit
  spec/type.dd
Labels: Bug Fix

#3507 Result of pure factory function
  spec/function.dd
Labels: auto-merge-squash

#3520 Issue 20997 - Missing example of scope guard executing after return statement
  spec/statement.dd
Labels: Enhancement

#3525 merge stable
  changelog/2.102.1_pre.dd
  download.dd
Labels: auto-merge, stable -> master

#3526 circleci: Increase memory allocated to the CI pipeline
  .circleci/config.yml
Labels: auto-merge, Continuous Integration

#3527 Update OpenBSD download link
  download.dd
Labels: auto-merge, links

#3528 d-keyring.gpg: Run gpg --refresh-keys
  d-keyring.gpg
  d-keyring.gpg.sig
  gpg_keys.dd
Labels: Easy Review

#3529 Donation page overhaul
  foundation/donate.dd
Labels: auto-merge

#3531 update download and changelog for v2.102.1
  VERSION
  changelog/2.102.1.dd
  download.dd
Labels: auto-merge, stable -> master

#3530 fix Issue 23716 - Document asm extension for ImportC
  spec/importc.dd
Labels: Bug Fix

#3535 fix Issue 23694 and Issue 23700 Document ImportC CTFE
  spec/importc.dd
Labels: Spec / content, auto-merge, Bug Fix, Easy Review

#3536 merge stable
  changelog/2.102.2_pre.dd
  download.dd
Labels: stable -> master

#3534 [spec] Improve `is(Type == keyword)` and Identifier docs
  spec/expression.dd
Labels: Enhancement

#3541 Suppress deprecation for format specification
  spec/arrays.dd
Labels: auto-merge

#3543 Missing space
  spec/operatoroverloading.dd
Labels: auto-merge

#3542 Fix typo
  spec/statement.dd
Labels: auto-merge
