Repository dlang/dlang.org, pull requests merged in 2023-03, with the labels that each got.

#3544 merge stable
  VERSION
  changelog/2.102.2.dd
  download.dd
Labels: auto-merge, stable -> master

#3545 update download and changelog for v2.103.0-beta.1
  changelog/2.103.0_pre.dd
  download.dd
Labels: auto-merge, stable -> master

#3547 Add GH sponsors to donate page
  foundation/donate.dd
Labels: auto-merge

#3555 update download and changelog for v2.103.0-rc.1
  changelog/2.103.0_pre.dd
  download.dd
Labels: auto-merge, stable -> master

#3556 Fix Issue 14932 - spec does not define what shared attribute does
  spec/attribute.dd
  spec/const3.dd
Labels: Bug Fix

#3563 [spec/struct] Tweak Copy Constructor docs
  spec/struct.dd
Labels: auto-merge
