Repository dlang/dlang.org, pull requests merged in 2023-11, with the labels that each got.

#3708 update download and changelog for v2.105.3
  VERSION
  changelog/2.105.3.dd
Labels: stable -> master

#3711 Remove outdated example for class .offsetof
  spec/class.dd
Labels: Spec / content

#3706 Improve function (pointer) type docs
  spec/function.dd
  spec/type.dd
Labels: Enhancement

#3701 [spec] Array literal can implicitly convert to an expected type
  spec/expression.dd
Labels: Enhancement, Bug Fix

#3699 [spec] Improve `opApply` docs
  spec/statement.dd
Labels: Enhancement

#3718 Mention C 'spiral rule', not 'right-left rule'
  spec/declaration.dd
Labels: auto-merge

#3698 Update index.dd
  index.dd
Labels: auto-merge

#3722 [spec] Improve function type (alias) docs
  spec/declaration.dd
  spec/type.dd
Labels: auto-merge

#3724 Fix issue 24239 - dlang.org tests on CircleCI run out of memory
  .circleci/run.sh
  posix.mak
Labels: Bug Fix

#3649 Specify safe values for `bool`
  spec/declaration.dd
  spec/function.dd
Labels: auto-merge

#3729 update download and changelog for v2.106.0-rc.1
  changelog/2.106.0_pre.dd
  download.dd
Labels: auto-merge

#3728 Add organization Tagion
  images/orgs-using-d/tagion.svg
  orgs-using-d.dd
Labels: auto-merge

#3732 updated __attribute__ and __declspec support
  spec/importc.dd
Labels: auto-merge, Easy Review

#3731 fix ImportC: Can use -> operator on non-pointer
  spec/importc.dd
Labels: auto-merge, Easy Review

#3734 Fix links in "Enum Copying and Assignment"
  spec/enum.dd
Labels: auto-merge
