Repository dlang/dlang.org, pull requests merged in 2024-07, with the labels that each got.

#3866 update download and changelog for v2.109.1
  VERSION
  changelog/2.109.1.dd
  download.dd
Labels: auto-merge

#3873 Clarify capacity documentation
  spec/arrays.dd
Labels: auto-merge

#3875 Add space between tokens
  spec/attribute.dd
Labels: auto-merge

#3876 Trivial formatting
  spec/statement.dd
Labels: auto-merge

#3880 [spec/function] Update @safe spec for safe values
  spec/function.dd
Labels: auto-merge

#3879 [spec/function] Add example for `ref return` void free function
  spec/function.dd
Labels: auto-merge

#3878 [spec/memory-safe-d] Improve `return` attribute docs
  spec/memory-safe-d.dd
Labels: Enhancement

#3884 Update DIP links
  .htaccess
Labels: Trivial, auto-merge

#3888 ddoc_preprocessor: Don't depend on entire DMD frontend, only include single `dmd.cli` module
  ddoc/dub.sdl
Labels: auto-merge

#3890 Remove dub.selections.json left-overs wrt. removed dmd dependency
  ddoc/dub.selections.json
  dpl-docs/dub.selections.json
Labels: auto-merge

#3889 Don't use deprecated posix.mak Makefiles for druntime and Phobos
  posix.mak
Labels: auto-merge

#3891 Allow variadic parameters with default in grammar
  spec/function.dd
Labels: auto-merge
