Repository dlang/dlang.org, pull requests merged in 2024-05, with the labels that each got.

#3819 [spec] Add grammar for `(Type)(args)` expression
  spec/expression.dd
Labels: Bug Fix

#3823 [spec] Improve module scope operator example
  spec/module.dd
Labels: auto-merge

#3822 [spec] Improve PrimaryExpression docs
  spec/expression.dd
Labels: auto-merge

#3827 Fix Bugzilla 24543 - The `@__future` attribute is (almost) undocumented
  spec/attribute.dd
  spec/traits.dd
Labels: Bug Fix

#3820 Update to special member functions ddoc in c++ interop
  spec/cpp_interface.dd
Labels: auto-merge-squash

#3830 Fix Bugzilla 24548 - [spec] Boolean condition conversion is not docum…
  spec/expression.dd
  spec/statement.dd
Labels: auto-merge, Bug Fix

#3834 [spec/type] Document integer implicit conversions
  spec/type.dd
Labels: auto-merge

#3836 [spec/function] Improve contract docs
  spec/function.dd
Labels: Bug Fix
