Repository dlang/dlang.org, pull requests merged in 2024-01, with the labels that each got.

#3753 merge stable
  VERSION
  changelog/2.106.1.dd
  download.dd
Labels: auto-merge, stable -> master

#3755 Fix Issue 24313 - Download page should reference Github nightlies
  download.dd
Labels: Enhancement, auto-merge

#3752 fix Issue 24310 - importC: Document workaround for using C symbols wh…
  spec/importc.dd
Labels: Enhancement, Spec / content, Bug Fix

#3756 fix Issue 24331 - @nogc and GC.disable() are often confused
  spec/function.dd
Labels: Enhancement, Spec / content, auto-merge, Improve, Easy Review

#3757 Update release schedule for 2024
  changelog/release-schedule.dd
Labels: Spec / content, auto-merge

#3758 [spec/declaration] Document field aliases
  spec/declaration.dd
Labels: auto-merge

#3764 listanchors.js: Match both dlang.org and docarchives.dlang.io in version selector
  js/listanchors.js
Labels: auto-merge

#3766 Fix path for querying druntime contributions
  js/show_contributors.js
Labels: auto-merge

#3760 Document hex strings
  spec/expression.dd
  spec/lex.dd
Labels: Spec / content, auto-merge
