Repository dlang/dlang.org, pull requests merged in 2024-04, with the labels that each got.

#3796 [spec] Update links to lvalue sequences
  spec/arrays.dd
  spec/class.dd
  spec/statement.dd
  spec/struct.dd
Labels: auto-merge

#3800 Fix Bugzilla 24472 - __traits(fullyQualifedName) is undocumented in spec
  spec/traits.dd
Labels: Bug Fix

#3802 Add Contributing page
  book/dlang.org.ddoc
  bugstats.dd
  contributing.dd
  dlang.org.ddoc
  posix.mak
Labels: Enhancement, auto-merge

#3803 correct minor misspelling of "reimplement" in articles/ctod.dd
  articles/ctod.dd
Labels: auto-merge

#3805 [deprecate] Hex strings are no longer deprecated
  deprecate.dd
Labels: auto-merge

#3810 Add more details on removing many C style cast errors.
  changelog/2.105.0.dd
Labels: auto-merge

#3813 [spec] `foreach_reverse` with a delegate is an error
  spec/statement.dd
Labels: Waiting for DMD PR

#3816 Fix some invalid links
  changelog/2.082.0.dd
  changelog/2.095.0.dd
  changelog/2.097.0.dd
  index.dd
  spec/cpp_interface.dd
  spec/importc.dd
Labels: auto-merge

#3817 Fix invalid link
  spec/type.dd
Labels: auto-merge
