Repository dlang/dlang.org, pull requests merged in 2024-11, with the labels that each got.

#3921 add __traits getBitfieldOffset and getBitfieldWidth
  spec/traits.dd
Labels: Enhancement, Spec / content, Waiting for DMD PR

#3922 [spec/expression] Fix C-style declaration for "In Expressions" example.
  spec/expression.dd
Labels: auto-merge

#3925 [spec/expression] Tweak postfix/callable expression docs
  spec/expression.dd
Labels: auto-merge

#3927 Fix Bugzilla 24876 - Undocumented cast from slice to static array
  spec/expression.dd
Labels: Enhancement, auto-merge

#3915 Fix Bugzilla 14945 - unions are missing from the ABI page
  spec/abi.dd
  spec/struct.dd
Labels: Bug Fix

#3928 Add new trait isCOMClass
  spec/traits.dd
Labels: auto-merge

#3930 Fix Bugzilla 24890 - spec/arrays.dd should mention comparison and war…
  spec/arrays.dd
  spec/function.dd
Labels: Enhancement
