Repository dlang/dlang.org, pull requests merged in 2024-02, with the labels that each got.

#3761 [spec/arrays] Improve string docs
  spec/arrays.dd
Labels: Bug Fix

#3771 ImportC: function-like macros
  spec/importc.dd
Labels: Spec / content

#3773 Use InterpolationExpressionSequence in grammar
  spec/expression.dd
  spec/template.dd
Labels: auto-merge

#3772 Fix grammar for InterpolatedTokenStringTokens
  spec/istring.dd
Labels: auto-merge
