Repository dlang/dlang.org, pull requests merged in 2025-03, with the labels that each got.

#4170 Mention the existence of the .tupleof property
  spec/property.dd
Labels: auto-merge

#4192 Fix issue #4191: The spec should warn against using mixin(__FUNCTION__)
  spec/expression.dd
Labels: Enhancement

#4185 Fix issue 4184: The spec should warn about using copy constructors.
  spec/struct.dd
Labels: 72h no objection -> merge
